services:
  spring-server:
    container_name: spring-server
    image: 430118823048.dkr.ecr.ap-northeast-2.amazonaws.com/moyeo:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10



