spring:
  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: dummy
            client-secret:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
          google:
            client-id: dummy
            client-secret: dummy
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - profile
              - email
            client-name: Google
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: dummy
  expirationMs: 1800000
  temp:
    expirationMs: 600000

default:
  image-url: dummy

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: dummy
      secret-key: dummy
    s3:
      bucket: dummy

server:
  port: 8080
  address: 0.0.0.0

openai:
  api-key: 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


kakao:
  api:
    key: 19833fa0c03fe54dcfa89fe0817defe0



---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/moyeo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
